% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={PSET 2 Stats ii RIPS},
  pdfauthor={Marcelo Piemonte Ribeiro},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{PSET 2 Stats ii RIPS}
\author{Marcelo Piemonte Ribeiro}
\date{4/18/2022}

\begin{document}
\maketitle

\hypertarget{question-1}{%
\subsection{Question 1}\label{question-1}}

\hypertarget{a}{%
\subsubsection{a)}\label{a}}

Estimate the effect of happiness (happiness) on the belief that there is
no need for democracy in the country (nodemo). This simple estimation
can be summarized by \(nodemo = \beta_0 +\beta_1happiness+u\). The table
below shows the significant negative association between them.

\begin{table}[!htbp] \centering 
  \caption{Table 1} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{1}{c}{\textit{Dependent variable:}} \\ 
\cline{2-2} 
\\[-1.8ex] & nodemo \\ 
\hline \\[-1.8ex] 
 happiness & $-$0.012$^{***}$ \\ 
  & (0.004) \\ 
  & \\ 
 Constant & 0.014$^{***}$ \\ 
  & (0.004) \\ 
  & \\ 
\hline \\[-1.8ex] 
Observations & 59,842 \\ 
R$^{2}$ & 0.0001 \\ 
Adjusted R$^{2}$ & 0.0001 \\ 
Residual Std. Error & 0.998 (df = 59840) \\ 
F Statistic & 8.600$^{***}$ (df = 1; 59840) \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{1}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table}

\hypertarget{b}{%
\subsubsection{b)}\label{b}}

To perform a pooled cross section, a new variable using the date of the
survey was created indicating the 13 weeks when the surveys were
conducted. In addition, 13 new dummy variables were created, and 12 of
them were added to the model as follow:
\(nodemo = \beta_0 +\beta_1happiness+week_2+ week_3+ week_4+ week_5+ week_6+ week_7+ week_8+ week_9+ week_{10}+ week_{11}+ week_{12}+ week_{13}+ u\).
The results changed with the inclusion of the time fixed effects,
\emph{happiness} still has the same negative significant effect but
slightly weaker. However, \emph{week\_\{11\}} and \emph{week\_\{12\}}
are significant in relation to the reference \emph{week\_1}. Therefore,
there are significant differences between the first week of survey and
the \emph{week\_\{11\}} and, especially, \emph{week\_\{12\}}, while for
the rest of the weeks, the intercept isn't significantly different from
\emph{week\_1}. The coefficient of \emph{week\_\{11\}} implies that,
holding \emph{happiness} constant, \emph{nodemo} is -0.27 lower in
\emph{week\_\{11\}} and -0.52 in \emph{week\_\{12\}} than
\emph{week\_1}, this effect in \emph{nodemo} is separate from the one in
\emph{nodemo} due to \emph{happiness} variation. \emph{week\_\{11\}} and
\emph{week\_\{12\}} coefficients represent drops in \emph{nodemo} for
reasons not captured by the independent variables, in this case
\emph{happiness}.

The week fixed effects allow us to verify over-time changes of the
dependent variable \emph{nodemo} by allowing the intercept to have
different values in each time period (weeks). A F-statistic test
rejected the null hypothesis that all coefficients on week dummies are
zero. By adding these dummies we allow the possibility of the population
to have different distributions in different time periods, so the
intercept can differ across periods (weeks). Therefore, we should add
the week-fixed effect if we suspect the relation between these variables
is not constant across the weeks.

\begin{table}[!htbp] \centering 
  \caption{Table 2} 
  \label{} 
\small 
\begin{tabular}{@{\extracolsep{5pt}}lcc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{2}{c}{\textit{Dependent variable:}} \\ 
\cline{2-3} 
\\[-1.8ex] & \multicolumn{2}{c}{nodemo} \\ 
 & OLS & Pooled-week \\ 
\\[-1.8ex] & (1) & (2)\\ 
\hline \\[-1.8ex] 
 Constant & 0.0144 (0.0041)$^{***}$ & 0.0081 (0.1055) \\ 
  happiness & $-$0.0120 (0.0041)$^{***}$ & $-$0.0089 (0.0041)$^{**}$ \\ 
  week\_2 &  & 0.0226 (0.1060) \\ 
  week\_3 &  & $-$0.0165 (0.1061) \\ 
  week\_4 &  & $-$0.0692 (0.1063) \\ 
  week\_5 &  & $-$0.0787 (0.1068) \\ 
  week\_6 &  & 0.0100 (0.1061) \\ 
  week\_7 &  & $-$0.0156 (0.1058) \\ 
  week\_8 &  & 0.1459 (0.1060) \\ 
  week\_9 &  & 0.1028 (0.1070) \\ 
  week\_10 &  & 0.0045 (0.1105) \\ 
  week\_11 &  & $-$0.2671 (0.1124)$^{**}$ \\ 
  week\_12 &  & $-$0.5186 (0.1187)$^{***}$ \\ 
  week\_13 &  & $-$0.0133 (0.2506) \\ 
 \hline \\[-1.8ex] 
Observations & 59,842 & 59,842 \\ 
R$^{2}$ & 0.0001 & 0.0060 \\ 
Adjusted R$^{2}$ & 0.0001 & 0.0058 \\ 
Residual Std. Error & 0.9977 (df = 59840) & 0.9949 (df = 59828) \\ 
F Statistic & 8.5996$^{***}$ (df = 1; 59840) & 27.7146$^{***}$ (df = 13; 59828) \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{2}{l}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
 & \multicolumn{2}{l}{datasets::freeny} \\ 
 & \multicolumn{2}{l}{lm() function} \\ 
 & \multicolumn{2}{l}{vcovHC(type = 'HC1')-Robust SE} \\ 
\end{tabular} 
\end{table}

\hypertarget{c}{%
\subsubsection{c)}\label{c}}

The previous exercise result assumed constant effect of the explanatory
variable across the weeks. To verify if in any week the main effect was
substantially larger or smaller than the first week, in other words to
check whether \emph{happiness} has varying effects on the outcome over
time, interacting it with week fixed effect dummies is necessary, such
as \(nodemo = \beta_0 +\beta_1happiness^*weeks +u\). Interacting it with
the time dummies, allows the slope coefficients to vary across different
periods.

The main effect of \emph{happiness} shows its estimated effect in
\emph{nodemo} for the base \emph{week\_1}. The table below shows how
\emph{happiness} coefficients vary , the interacted coefficients show
the estimated differences in the effect of \emph{happiness} on
\emph{nodemo} from \emph{week\_1} to each week, respectively. For
example, for the sample of \emph{week\_5}, the estimated effect of
\emph{happiness} on the outcome is roughly 0.075 (= -0.2980+0.3735),
therefore no longer a negative effect. A F-statistic test rejected the
null hypothesis that all interacted coefficients are zero

\begin{table}[!htbp] \centering 
  \caption{Table 3} 
  \label{} 
\small 
\begin{tabular}{@{\extracolsep{5pt}}lccc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\ 
\cline{2-4} 
\\[-1.8ex] & \multicolumn{3}{c}{nodemo} \\ 
 & OLS & Pooled-week & Pooled_week-interaction \\ 
\\[-1.8ex] & (1) & (2) & (3)\\ 
\hline \\[-1.8ex] 
 Constant & 0.0144 (0.0041)$^{***}$ & 0.0081 (0.1055) & 0.0356 (0.1063) \\ 
  happiness & $-$0.0120 (0.0041)$^{***}$ & $-$0.0089 (0.0041)$^{**}$ & $-$0.2980 (0.1541)$^{**}$ \\ 
  week\_2 &  & 0.0226 (0.1060) &  \\ 
  week\_3 &  & $-$0.0165 (0.1061) &  \\ 
  week\_4 &  & $-$0.0692 (0.1063) &  \\ 
  week\_5 &  & $-$0.0787 (0.1068) &  \\ 
  week\_6 &  & 0.0100 (0.1061) &  \\ 
  week\_7 &  & $-$0.0156 (0.1058) &  \\ 
  week\_8 &  & 0.1459 (0.1060) &  \\ 
  week\_9 &  & 0.1028 (0.1070) &  \\ 
  week\_10 &  & 0.0045 (0.1105) &  \\ 
  week\_11 &  & $-$0.2671 (0.1124)$^{**}$ &  \\ 
  week\_12 &  & $-$0.5186 (0.1187)$^{***}$ &  \\ 
  week\_13 &  & $-$0.0133 (0.2506) &  \\ 
  factor(week)2 &  &  & $-$0.0089 (0.1068) \\ 
  factor(week)3 &  &  & $-$0.0411 (0.1068) \\ 
  factor(week)4 &  &  & $-$0.0966 (0.1071) \\ 
  factor(week)5 &  &  & $-$0.1098 (0.1076) \\ 
  factor(week)6 &  &  & $-$0.0168 (0.1068) \\ 
  factor(week)7 &  &  & $-$0.0426 (0.1066) \\ 
  factor(week)8 &  &  & 0.1192 (0.1068) \\ 
  factor(week)9 &  &  & 0.0648 (0.1078) \\ 
  factor(week)10 &  &  & $-$0.0238 (0.1115) \\ 
  factor(week)11 &  &  & $-$0.2950 (0.1134)$^{***}$ \\ 
  factor(week)12 &  &  & $-$0.5339 (0.1205)$^{***}$ \\ 
  factor(week)13 &  &  & $-$0.0179 (0.2296) \\ 
  happiness:factor(week)2 &  &  & 0.3379 (0.1544)$^{**}$ \\ 
  happiness:factor(week)3 &  &  & 0.2146 (0.1545) \\ 
  happiness:factor(week)4 &  &  & 0.2854 (0.1547)$^{**}$ \\ 
  happiness:factor(week)5 &  &  & 0.3735 (0.1551)$^{***}$ \\ 
  happiness:factor(week)6 &  &  & 0.2441 (0.1545)$^{*}$ \\ 
  happiness:factor(week)7 &  &  & 0.3126 (0.1544)$^{**}$ \\ 
  happiness:factor(week)8 &  &  & 0.3007 (0.1545)$^{**}$ \\ 
  happiness:factor(week)9 &  &  & 0.2475 (0.1551)$^{*}$ \\ 
  happiness:factor(week)10 &  &  & 0.2858 (0.1567)$^{*}$ \\ 
  happiness:factor(week)11 &  &  & 0.2929 (0.1584)$^{*}$ \\ 
  happiness:factor(week)12 &  &  & 0.2344 (0.1585) \\ 
  happiness:factor(week)13 &  &  & $-$0.0590 (0.1869) \\ 
 \hline \\[-1.8ex] 
Observations & 59,842 & 59,842 & 59,842 \\ 
R$^{2}$ & 0.0001 & 0.0060 & 0.0082 \\ 
Adjusted R$^{2}$ & 0.0001 & 0.0058 & 0.0078 \\ 
Residual Std. Error & 0.9977 (df = 59840) & 0.9949 (df = 59828) & 0.9939 (df = 59816) \\ 
F Statistic & 8.5996$^{***}$ (df = 1; 59840) & 27.7146$^{***}$ (df = 13; 59828) & 19.8018$^{***}$ (df = 25; 59816) \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{3}{l}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
 & \multicolumn{3}{l}{datasets::freeny} \\ 
 & \multicolumn{3}{l}{lm() function} \\ 
 & \multicolumn{3}{l}{vcovHC(type = 'HC1')-Robust SE} \\ 
\end{tabular} 
\end{table}

\hypertarget{d}{%
\subsubsection{d)}\label{d}}

First of all, as done in Jiang, J., \& Yang, D. L. (2016) p.607, we
restrict our dataset such that we exclude respondents from provinces
where all interviews were conducted either before or after 26/09. As in
the paper, the number of provinces included in the sample decreases from
28 to 12.

It is possible to verify the mean performing the regression
\(nodemo = \beta_0 +\beta_1shanghai +u\). While the mean value of
\emph{nodemo} outside Shaghai was 0.0623 (the intercept of the below
regression result), in shanghai this value was 0.1440. The significant
p-value confirms the difference of these averages.

\begin{table}[!htbp] \centering 
  \caption{Table 4} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{1}{c}{\textit{Dependent variable:}} \\ 
\cline{2-2} 
\\[-1.8ex] & nodemo \\ 
\hline \\[-1.8ex] 
 shanghai & 0.144$^{***}$ \\ 
  & (0.028) \\ 
  & \\ 
 Constant & 0.062$^{***}$ \\ 
  & (0.009) \\ 
  & \\ 
\hline \\[-1.8ex] 
Observations & 15,894 \\ 
R$^{2}$ & 0.002 \\ 
Adjusted R$^{2}$ & 0.002 \\ 
Residual Std. Error & 1.073 (df = 15892) \\ 
F Statistic & 26.812$^{***}$ (df = 1; 15892) \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{1}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table}

\hypertarget{e}{%
\subsubsection{e)}\label{e}}

The previous exercise compares the averages only taking into account
weeks after the purge, therefore, it does not consider whether
\emph{nodemo} in Shanghai and in other regions differed or not before
the purge, which could modify such difference. The result below compares
the same averages of the previous exercise but restricting the data to
those districts where respondents were surveyed before the purge. The
insignificant p-value shows that the difference between the regions was
negligible before the purge.

\begin{table}[!htbp] \centering 
  \caption{Table 4} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{1}{c}{\textit{Dependent variable:}} \\ 
\cline{2-2} 
\\[-1.8ex] & nodemo \\ 
\hline \\[-1.8ex] 
 shanghai & $-$0.004 \\ 
  & (0.039) \\ 
  & \\ 
 Constant & $-$0.066$^{***}$ \\ 
  & (0.009) \\ 
  & \\ 
\hline \\[-1.8ex] 
Observations & 13,889 \\ 
R$^{2}$ & 0.00000 \\ 
Adjusted R$^{2}$ & $-$0.0001 \\ 
Residual Std. Error & 1.000 (df = 13887) \\ 
F Statistic & 0.011 (df = 1; 13887) \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{1}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table}

\hypertarget{f}{%
\subsubsection{f)}\label{f}}

The charts below compares the \emph{nodemo} averages of Shanghai and
other regions respondents according to the weeks and days the surveys
took place and the periods before and after the purge. A standard DiD
equation would be \(nodemo = \beta_0 +\beta_1shanghai^*treat +u\), where
\emph{shanghai} determines the two control and treatment groups while
\emph{treat} indicate the survey's dates before and after the purge.

\includegraphics{PSET2_STATSII_RIPS_PIEMONTE-RIBEIRO_files/figure-latex/q1f_ggplot-1.pdf}

\includegraphics{PSET2_STATSII_RIPS_PIEMONTE-RIBEIRO_files/figure-latex/q1f_ggplot2-1.pdf}

\includegraphics{PSET2_STATSII_RIPS_PIEMONTE-RIBEIRO_files/figure-latex/q1f_ggplot3-1.pdf}

\begin{table}[!htbp] \centering 
  \caption{Table 5} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{1}{c}{\textit{Dependent variable:}} \\ 
\cline{2-2} 
\\[-1.8ex] & nodemo \\ 
\hline \\[-1.8ex] 
 shanghai & $-$0.004 \\ 
  & (0.040) \\ 
  & \\ 
 treat & 0.129$^{***}$ \\ 
  & (0.013) \\ 
  & \\ 
 shanghai:treat & 0.148$^{***}$ \\ 
  & (0.048) \\ 
  & \\ 
 Constant & $-$0.066$^{***}$ \\ 
  & (0.009) \\ 
  & \\ 
\hline \\[-1.8ex] 
Observations & 29,783 \\ 
R$^{2}$ & 0.006 \\ 
Adjusted R$^{2}$ & 0.006 \\ 
Residual Std. Error & 1.040 (df = 29779) \\ 
F Statistic & 56.781$^{***}$ (df = 3; 29779) \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{1}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table}

In the above model, the DiD estimator is the coefficient on the
interaction term, 0.1480, which shows the difference in the average
change over time for the treatment and control groups. It confirms the
previous exercises as \emph{shanghai} coefficients difference
(0.1440-(-0.004)=0.148) is equal the interacted term. Therefore, the
purge increased \emph{nodemo} by 0.148.

\hypertarget{g-and-h}{%
\subsubsection{g and h)}\label{g-and-h}}

So far, we assumed all was constant except the effect of the purge and
that the impact of the purge was the same everywhere. Including these
fixed effects should help the estimation as they go in line with the
needed assumptions of a DiD model. Such model assumes compositional
change across the weeks before and after the purge and that time trends
might not be comparable across the treated and control groups. DiD here
works because the assumption is that people in Shanghai were more
treated than the rest, this is why we include the Shanghai dummy.

\hypertarget{i-and-j}{%
\subsubsection{i and j)}\label{i-and-j}}

The DiD equation can be rewritten as follow:
\(nodemo = \beta_0 +\beta_1shanghai^*treat + \beta_2province +\beta_3date + \beta_4age + \beta_5college + \beta_6working + \beta_7party +u\).
Comparing to previous results, the below table presents a higher effect
of the interacted term, indicating the relatively stronger effect in
Shanghai. Also, \emph{treat} becomes no longer significant, but
\emph{date} does as well as the other independent variable, except
\emph{shanghai}.

\begin{table}[!htbp] \centering 
  \caption{Table 6} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{1}{c}{\textit{Dependent variable:}} \\ 
\cline{2-2} 
\\[-1.8ex] & nodemo \\ 
\hline \\[-1.8ex] 
 shanghai & 0.037 \\ 
  & (0.040) \\ 
  & \\ 
 treat & $-$0.005 \\ 
  & (0.019) \\ 
  & \\ 
 province & 0.019$^{***}$ \\ 
  & (0.001) \\ 
  & \\ 
 date & 0.004$^{***}$ \\ 
  & (0.001) \\ 
  & \\ 
 age & 0.004$^{***}$ \\ 
  & (0.0005) \\ 
  & \\ 
 college & $-$0.051$^{**}$ \\ 
  & (0.021) \\ 
  & \\ 
 working & $-$0.034$^{***}$ \\ 
  & (0.013) \\ 
  & \\ 
 party & $-$0.199$^{***}$ \\ 
  & (0.022) \\ 
  & \\ 
 shanghai:treat & 0.169$^{***}$ \\ 
  & (0.048) \\ 
  & \\ 
 Constant & $-$57.673$^{***}$ \\ 
  & (10.638) \\ 
  & \\ 
\hline \\[-1.8ex] 
Observations & 29,783 \\ 
R$^{2}$ & 0.035 \\ 
Adjusted R$^{2}$ & 0.035 \\ 
Residual Std. Error & 1.024 (df = 29773) \\ 
F Statistic & 120.233$^{***}$ (df = 9; 29773) \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{1}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table}

\hypertarget{j}{%
\subsubsection{j)}\label{j}}

The cut-off points were determined by the variable \emph{treat} which
takes the date of 26/09. To simulate other cutoffs, new variables were
created: \emph{treat\_1} equals 19/09, \emph{treat\_2} 3/10,
\emph{treat\_3} 10/10 and \emph{treat\_4} 17/10.

\begin{table}[!htbp] \centering 
  \caption{Table 7} 
  \label{} 
\small 
\begin{tabular}{@{\extracolsep{5pt}}lcccccc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{6}{c}{\textit{Dependent variable:}} \\ 
\cline{2-7} 
\\[-1.8ex] & \multicolumn{6}{c}{nodemo} \\ 
 & No control & Purge 26/09 & Purge 19/09 & Purge 03/10 & Purge 10/10 & Purge 17/10 \\ 
\\[-1.8ex] & (1) & (2) & (3) & (4) & (5) & (6)\\ 
\hline \\[-1.8ex] 
 Constant & $-$0.0662 (0.0088)$^{***}$ & $-$57.6729 (10.9995)$^{***}$ & $-$71.1641 (9.0497)$^{***}$ & $-$30.6789 (12.4655)$^{**}$ & 49.0528 (12.1621)$^{***}$ & $-$49.6103 (9.2087)$^{***}$ \\ 
  shanghai & $-$0.0041 (0.0329) & 0.0368 (0.0327) & $-$0.0930 (0.0398) & 0.0856 (0.0307)$^{***}$ & 0.1605 (0.0262)$^{***}$ & 0.1080 (0.0244)$^{***}$ \\ 
  treat & 0.1285 (0.0125)$^{***}$ & $-$0.0045 (0.0193) &  &  &  &  \\ 
  treat\_1 &  &  & $-$0.0524 (0.0185)$^{***}$ &  &  &  \\ 
  treat\_2 &  &  &  & 0.0643 (0.0256)$^{***}$ &  &  \\ 
  treat\_3 &  &  &  &  & 0.2953 (0.0277)$^{***}$ &  \\ 
  treat\_4 &  &  &  &  &  & 0.0137 (0.0272) \\ 
  province &  & 0.0187 (0.0009)$^{***}$ & 0.0182 (0.0009)$^{***}$ & 0.0184 (0.0009)$^{***}$ & 0.0170 (0.0009)$^{***}$ & 0.0188 (0.0009)$^{***}$ \\ 
  date &  & 0.0043 (0.0008)$^{***}$ & 0.0053 (0.0007)$^{***}$ & 0.0023 (0.0009)$^{**}$ & $-$0.0037 (0.0009)$^{***}$ & 0.0037 (0.0007)$^{***}$ \\ 
  age &  & 0.0043 (0.0005)$^{***}$ & 0.0043 (0.0005)$^{***}$ & 0.0043 (0.0005)$^{***}$ & 0.0041 (0.0005)$^{***}$ & 0.0043 (0.0005)$^{***}$ \\ 
  college &  & $-$0.0511 (0.0222)$^{**}$ & $-$0.0503 (0.0223)$^{**}$ & $-$0.0518 (0.0222)$^{**}$ & $-$0.0361 (0.0224)$^{*}$ & $-$0.0500 (0.0222)$^{**}$ \\ 
  working &  & $-$0.0342 (0.0129)$^{***}$ & $-$0.0356 (0.0128)$^{***}$ & $-$0.0363 (0.0129)$^{***}$ & $-$0.0435 (0.0129)$^{***}$ & $-$0.0355 (0.0129)$^{***}$ \\ 
  party &  & $-$0.1992 (0.0216)$^{***}$ & $-$0.1989 (0.0216)$^{***}$ & $-$0.1990 (0.0217)$^{***}$ & $-$0.1940 (0.0217)$^{***}$ & $-$0.1988 (0.0216)$^{***}$ \\ 
  shanghai:treat & 0.1480 (0.0442)$^{***}$ & 0.1688 (0.0439)$^{***}$ &  &  &  &  \\ 
  shanghai:treat\_1 &  &  & 0.2837 (0.0471)$^{***}$ &  &  &  \\ 
  shanghai:treat\_2 &  &  &  & 0.1127 (0.0454)$^{**}$ &  &  \\ 
  shanghai:treat\_3 &  &  &  &  & 0.0237 (0.0527) &  \\ 
  shanghai:treat\_4 &  &  &  &  &  & 0.2806 (0.0648)$^{***}$ \\ 
 \hline \\[-1.8ex] 
Observations & 29,783 & 29,783 & 29,783 & 29,783 & 29,783 & 29,783 \\ 
R$^{2}$ & 0.0057 & 0.0351 & 0.0355 & 0.0352 & 0.0385 & 0.0355 \\ 
Adjusted R$^{2}$ & 0.0056 & 0.0348 & 0.0352 & 0.0349 & 0.0382 & 0.0352 \\ 
Residual Std. Error & 1.0398 (df = 29779) & 1.0244 (df = 29773) & 1.0242 (df = 29773) & 1.0243 (df = 29773) & 1.0226 (df = 29773) & 1.0242 (df = 29773) \\ 
F Statistic & 56.7806$^{***}$ (df = 3; 29779) & 120.2326$^{***}$ (df = 9; 29773) & 121.6472$^{***}$ (df = 9; 29773) & 120.7239$^{***}$ (df = 9; 29773) & 132.3011$^{***}$ (df = 9; 29773) & 121.7321$^{***}$ (df = 9; 29773) \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{6}{l}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
 & \multicolumn{6}{l}{datasets::freeny} \\ 
 & \multicolumn{6}{l}{lm() function} \\ 
 & \multicolumn{6}{l}{vcovHC(type = 'HC1')-Robust SE} \\ 
\end{tabular} 
\end{table}

\end{document}
